# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('photo', models.ImageField(upload_to='')),
                ('birth_date', models.DateTimeField(verbose_name='bith date')),
            ],
        ),
    ]
