# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import miapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=miapp.models.user_directory_path),
        ),
    ]
