# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_auto_20161103_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='birth_date',
        ),
    ]
